version: '3.7'

services:
  shop:
    build: .
    command: java -jar /home/service/shop-1.0.jar
    container_name: shop
    restart: unless-stopped
    ports:
      - "8200:8200"
    depends_on:
      - shop_db
    environment:
      - POSTGRES_URL=shop_db:5432
      - POSTGRES_USER=shop_adm
      - POSTGRES_PASSWORD=root

  shop_db:
    image: postgres:12-alpine
    container_name: shop_db
    environment:
      - POSTGRES_USER=shop_adm
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shop_db

  maildev:
    container_name: shop-maildev
    image: maildev/maildev
    ports:
      - "2080:80"
      - "25:25"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: notifications:1:1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

