version: '3.7'
x-healthcheck:
  &health_check
  interval: 1m
  timeout: 10s
  retries: 2
  start_period: 1m
services:

  study_shop_postgres:
    image: postgres:12
    ports:
      - 55432:5432
    networks:
      - network1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      <<: *health_check
      test: pg_isready -U postgres

  study_shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study_shop
    ports:
      - 8080:8189
    environment:
      - POSTGRES_URL=study_shop_postgres:5432
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    depends_on:
      - study_shop_postgres
    networks:
      - network1
    entrypoint: sh -c "java -jar /home/service/study_shop-0.0.1-SNAPSHOT.jar"

networks:
  network1:
    driver: bridge
