version: '3.7'

services:
  shop:
    build: .
    command: java -jar /home/service/shop-1.0.jar
    container_name: shop
    restart: unless-stopped
    ports:
      - "8200:8200"
    networks:
      - shopNetwork
    depends_on:
      - shop_db
    environment:
      - POSTGRES_URL=shop_db:5432
      - POSTGRES_USER=shop_adm
      - POSTGRES_PASSWORD=root

  shop_db:
    image: postgres:12-alpine
    container_name: shop_db
    networks:
      - shopNetwork
    environment:
      - POSTGRES_USER=shop_adm
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shop_db

  maildev:
    container_name: shop-maildev
    image: maildev/maildev
    ports:
      - "2080:80"
      - "25:25"
    networks:
      - shopNetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    networks:
      - shopNetwork
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: basket:1:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "22181:2181"
    networks:
      - shopNetwork
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

networks:
  shopNetwork:
    driver: bridge
