version: '3.7'

services:
  shop:
    build: .
    command: java -jar /home/service/shop-1.0.jar
    container_name: shop
    restart: unless-stopped
    ports:
      - "8200:8200"
    depends_on:
      - shop_db
    environment:
      - POSTGRES_URL=shop_db:5432

  shop_db:
    image: postgres:12-alpine
    container_name: shop_db
    environment:
      - POSTGRES_USER=shop_adm
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shop_db
