version: '3.7'

services:
  registry:
    image: registry:2
    container_name: shop-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - data:/var/lib/registry

volumes:
  data: