server:
  port: 8200
  servlet:
    context-path: /shop

spring:
  jpa:
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: file:///${user.dir}/src/main/resources/templates/
    cache: false
    mode: HTML

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/shop?currentSchema=shop
    username: postgres
    password: ${POSTGRES_PASSWORD:root}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

mail:
  user:
    login: vy.savinov@yandex.ru
    password: {MAIL_USER_PASSWORD}
  host: imap.yandex.ru
  inbox:
    protocol: imaps

  smtp:
    host: smtp.yandex.ru
    ssl:
      enable: true
      port: 465
      auth: true




