server:
  port: 8200

spring:
  jpa:
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/shop_db
    username: shop_adm
    password: ${POSTGRES_PASSWORD:root}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

mail:
  user:
    login: vy.savinov@yandex.ru
    password: ${MAIL_USER_PASSWORD:defaultValue}
  host: imap.yandex.ru
  inbox:
    protocol: imaps

  smtp:
    host: smtp.yandex.ru
    ssl:
      enable: true
      port: 465
      auth: true




