server:
  port: 8189
  servlet:
    context-path: /shop

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
  thymeleaf:
    prefix: file:///${user.dir}/src/main/resources/templates/
    cache: false
    mode: HTML

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/postgres?currentSchema=shop
    username: postgres
    password: ${POSTGRES_PASSWORD:root}


